development:
  adapter: postgresql
  database: AnniversaryStage_dev
  username: postgres
  password: 
  host: localhost

test:
  adapter: postgresql
  database: AnniversaryStage_test
  username: postgres
  password: 
  host: localhost

production:
  adapter: postgresql
  database: AnniversaryStage_live
  username: postgres
  password: 
  host: localhost